### ISSUE TITLE
No effect in kanboard v1.2.19

### ISSUE THREAD

**Issue by howie6879** [elaubmey/kanboard-Subtasktextfield#1]
Hi, this project seems to have no effect in kanboard v1.2.19

**Comment by collector-ynh** [comment]
> Hi, this project seems to have no effect in kanboard v1.2.19

For the plugin to work, it is necessary to name the folder **plugins/SubtaskTextfield** and not **plugins/Subtasktextfield**, the description in the Readme is misleading.

**Comment by howie6879** [comment]
thx

**Comment by elaubmey** [comment]
Thx for the answer, I don't saw the entry. 

I will corrext the readme.

Sorry for the misspelling
